import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/shadcnui/ui/tooltip";
import { Navigation } from "@/ui/modules/navigation/navigation";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className={cn("h-full", "antialiased", "font-sans", poppins.variable)}
    >
      <body className="min-h-full flex flex-col">
        <TooltipProvider>
          <Navigation />
          <span>{children}</span>
        </TooltipProvider>
      </body>
    </html>
  );
}
